http:
  addr: ":8080"

paths:
  ndpi_rules_local: "rules/ndpi/"
  suricata_template: "config/suricata.yaml.tpl"
  suricatasc: "/usr/local/bin/suricatasc"

suricata:
  socket_candidates:
    - "/run/suricata/suricata-command.socket"
    - "/var/run/suricata/suricata-command.socket"
  config_candidates:
    - "/etc/suricata/suricata.yaml"
    - "/usr/local/etc/suricata/suricata.yaml"

apply:
  overwrite_suricata_yaml: true      # если false - микросервис не пишет /etc/suricata/suricata.yaml
  restart_if_yaml_changed: true      # если шаблон изменил YAML - делаем рестарт

reload:
  timeout: "3m"
  command: "reload-rules"

system:
  systemctl: "/usr/bin/systemctl"
  suricata_service: "suricata"