name: test rules
on:
  push:
    branches:
      - sobik

jobs:
  validate_rules:
    name: check
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: sh
        working-directory: ./scripts
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create bin dir and add scripts
        run: |
          mkdir bin && ls
          cd bin
          mv ../test_rules.sh .
          ls
      - name: Run the script
        run: test_rules.sh
