name: test rules
on:
  push:
    branches:
      - 'main'
    paths:
      - 'rules/manual/rules.rules'

jobs:
  validate_rules:
    name: check
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    defaults:
      run:
        shell: bash
        working-directory: ./scripts

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

        with:
          fetch-depth: 0
          token: ${{ secrets.MY_PAT_TOKEN }}

      - name: Make the script files executable
        run: chmod +x rules_validation_script.sh
      - name: Run the script
        run: ./rules_validation_script.sh
      - name: Commit and push if changed

        run: |
          git config --local user.email "test@test.com"
          git config --local user.name "Test"
          git commit -a -m "Rewriting valid rules"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.MY_PAT_TOKEN }}
          repository: ISnDead/Integration-Suricata-nDPI
          force_with_lease: true